### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [dajare/mark-rutherford_mark-rutherfords-deliverance#1]
# General Issues:

- [x] I recommend that you remove `[Editorial]` from the commit [[Editorial] Fix printer typo in nested speech](https://github.com/dajare/mark-rutherford_mark-rutherfords-deliverance/commit/6eabc3e824af5aedf52c1ee027e184ab50b87f37). Fixing typos isn't considered editorial.

# epigraph.xhtml:

- [x] You will need to use `<i xml:lang="LANG">` for the foreign phrases, since the English translations should be in italics.

- [x] `De Imitatione Christi` should have `<i epub:type="se:name.publication.book" xml:lang="la">` semantics.

**Comment by dajare** [comment]
Thanks for this @EmmaSweeney ! I'll get to this tomorrow (I hope - just shutting down for the night now).

Just a quick comment on removing `[Editorial]` from that commit - I can/will do, but this is what the [Step-by-step guide][1] has under proof-reading:

> Printer’s errors. . . . If you spot an obvious error like this that is present in both the transcription and the page scans, it may be a printer’s error that should be corrected in an [Editorial] commit.

I guess this is one of those points where there's been some slippage between guidance and practice! 🤷‍♂️ 

[1]: https://standardebooks.org/contribute/producing-an-ebook-step-by-step#proofread "Under the 'Common proofreading issues' heading"

**Comment by dajare** [comment]
@EmmaSweeney - Now I check the epigraph *language* semantics (you're asking for `<i ...` tags) — lint complains if I put those in `<i ...` tags which is [how I had them originally][1], probably because they *are* italicized by the CSS rules in local.css? If you open the file in a browser, you'll see they are italicized.

(And how I got "play" for "book" ?!!)

Could you confirm that you want me to do this? If so, I expect I'll need an se-lint-ignore.xml file, too. Thanks!


[1]: https://github.com/dajare/mark-rutherford_mark-rutherfords-deliverance/commit/2bc04c9b582a92f5160b6cacc27c6caa54b9af46

**Comment by EmmaSweeney** [comment]
I wouldn't mark that printer error as [Editorial] because incorrect quotes happen so often.

In this case, lint is wrong. _Half_ of the text is non-English. You will need to add a se-lint-ignore.xml file.

**Comment by dajare** [comment]
I've addressed the italics/language issue in `epigraph.xhtml` — I hope correctly!

If any tweaks are needed, do tell; otherwise if you're content, this is ready for Alex. Thanks for your help!
